services:
  # 1. Backend Service
  - type: web
    name: edupulse-api
    env: node
    plan: free
    region: frankfurt # Yevropa serveri (O'zbekistonga yaqinroq)
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        sync: false # Buni Render dashboardda o'zingiz kiritasiz
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production

  # 2. Frontend (Static Site)
  - type: static
    name: edupulse-web
    env: static
    plan: free
    region: frankfurt
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: edupulse-api
          property: host
